name: phpunit

on:
    push:
    pull_request:

jobs:
    phpunit:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [8.0, 8.1, 8.2]
                laravel: [8.*, 9.*]
                stability: [prefer-lowest, prefer-stable]
                include:
                    - laravel: 8.*
                    - laravel: 9.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/phpunit
